<?php

namespace Application\Entity\Professional;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * SalonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalonRepository extends EntityRepository
{
    public function __construct($em)
    {
        $entityName = 'Application\Entity\Professional\Salon';
        $class = new ClassMetadata($entityName);

        parent::__construct($em, $class);
    }
}
