# docker-compose configuration for local development
#
# API STACK
# =========

front:
  build: .
  ports:
    - "80:80"
    - "9000:9000"
  links:
    - db:DB
  volumes:
    - application:/var/www/szepul.hu
  environment:
    APP_DEBUG: 1
    APP_ENV: dev
    NGINX_SERVER_NAMES: szepul.hu.dev www.szepul.hu.dev

db:
  image: mysql
  volumes:
    - docker/mysql:/var/lib/mysql
  ports:
    - "3306"
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: secretroot
    MYSQL_USER: dev
    MYSQL_PASSWORD: dev123
    MYSQL_DATABASE: dev-szepulhu
