#!/bin/bash

echo
read -p "Enter your Github API token if you have any otherwise leave this blank [ENTER]: " githubapitoken
echo
read -p "Enter the IP address of your default DNS server (see /etc/resolv.conf) [ENTER]: " dns_server_ip
echo

echo
echo "Determining Docker IP..."
dockerip=$(ifconfig docker0 2> /dev/null | grep --word-regexp inet | awk '{print $2}' | sed 's%addr:%%g')
dockerinterfaceip=$dockerip
if [[ ! $dockerip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] ; then
    dockerip=$(docker-machine ip default 2> /dev/null)
    if [[ ! $dockerip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] ; then
        echo "Can't determine Docker's IP address"
        exit -1
    fi
    subnet=${dockerip%.*}
    dockerinterfaceip=$(ifconfig 2> /dev/null | grep -F "inet $subnet" | awk '{print $2}' | sed 's%addr:%%g')
fi

echo
echo "Writing environment file..."
echo "APP_ENV=dev
APP_DEBUG=1
MYSQL_USER=dev
MYSQL_PASSWORD=123pass
MYSQL_ROOT_PASSWORD=supersecret
MYSQL_DATABASE=szepulhu_db
MYSQL_DATA_DIR=/var/lib/mysql-fixtures
DOCKER_IP=$dockerip
DOCKER_INTERFACE_IP=$dockerinterfaceip
GITHUB_API_TOKEN=$githubapitoken" > .env

echo "DNS_DOMAIN=dev
DNS_RECURSOR=$dns_server_ip" > .env-dns

echo
echo "Writing PHP config file..."
echo "; XDebug configuration
xdebug.remote_enable = 1
xdebug.renite_enable = 1
xdebug.max_nesting_level = 1000
xdebug.profiler_enable_trigger = 1
xdebug.profiler_output_dir = \"/var/log\"
xdebug.default_enable = 1
xdebug.remote_autostart = 0
xdebug.remote_handler = dbgp
xdebug.remote_port = 9000
xdebug.remote_connect_back = Off
xdebug.remote_host = $dockerinterfaceip

cgi.fix_pathinfo = 0
date.timezone = \"Europe/Budapest\"" > docker/services/php5-fpm/php.ini

echo "To be able to resolve containers from the host by hostname, the IP of the 'docker0' interface ($dockerip) must be
added to the /etc/resolv.conf file as the first server. After manual setup you should see something like this:

# Generated by resolvconf
search lan
nameserver $dockerip
"

echo
echo "Ok, your files are ready. From now you can use build.sh to build up your environment."
