parameters:
    template.strip_strict_tags: true
    i18n.format.pattern_map:
    -   source: ICU
        destination: jQuery
        mapping:
            EEEE: EE
            EEE: E
            EE: E
            MMMM: MM
            MMM: M
            MM: mm
            M: m
            yyyy: yy
            yy: y
            y: yy
services:
    twig.extension.intl:
            class: Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }

    twig.global.scripts:
        class: Application\Helper\Template\Scripts
        arguments: [ %template.strip_strict_tags% ]

    twig.global.format.converter:
        class: Application\Model\I18n\Format\PatternConverter
        arguments: [ %i18n.format.pattern_map% ]

    app.professional_repository:
        class: Application\Entity\ProfessionalUserRepository
        arguments:
            - @doctrine.orm.default_entity_manager

    app.salon_repository:
        class: Application\Entity\Professional\SalonRepository
        arguments:
            - @doctrine.orm.default_entity_manager

    app.county_repository:
        class: Application\Entity\CountyRepository
        arguments:
            - @doctrine.orm.default_entity_manager

    app.city_repository:
        class: Application\Entity\CityRepository
        arguments:
            - @doctrine.orm.default_entity_manager

    app.locator:
        class: Application\Model\Locator
        arguments:
            - @app.city_repository
            - @app.county_repository

    app.homepage.interactor:
        class: Application\Interactor\HomepageInteractor
        arguments:
            - @app.professional_repository
            - @app.county_repository
            - @app.city_repository
            - @app.locator
            - @form.factory

    app.professional.profile.interactor:
        class: Application\Interactor\ProfessionalProfileInteractor
        arguments:
            - @app.professional_repository

    app.salon.interactor:
        class: Application\Interactor\SalonInteractor
        arguments:
            - @app.salon_repository

    app.default_controller:
        class: Application\Controller\DefaultController
        arguments:
            - @templating
            - @app.homepage.interactor

    app.professional_controller:
        class: Application\Controller\ProfessionalController
        arguments:
            - @templating
            - @app.professional.profile.interactor
            - @app.salon.interactor
        calls:
            - [ setContainer, [@service_container] ]

    app.professional_registration:
        class: Application\EventListener\RegistrationSubscriber
        tags:
            - { name: kernel.event_subscriber }

    app.form.flow.register_professional:
        class: Application\Form\RegisterProfessionalFlow
        parent: craue.form.flow
        scope: request

    app.twig.extension:
        class: Application\Twig\Extension\SzepulhuExtension
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

    app.router:
        class: Application\Symfony\Component\Routing\Router
        public: false
        decorates: router.default
        arguments:
            - @app.router.inner

    app.form.type.location:
        class: Application\Form\Type\Professional\LocationType
        arguments:
            - @doctrine.orm.default_entity_manager
        tags:
            - { name: form.type, alias: location }
