<?php

namespace Application\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientUserRepository extends EntityRepository
{
}
