Application\Entity\Professional\ServiceGroup:
    service_group_{1..21}:
        name: <serviceGroup()>
        professional: @professional_*
    service_group_22:
        name: Haj
        professional: @professional_15

Application\Entity\Professional\Service:
    service_{1..30}:
        name: <service()>
        description: <paragraph(2)>
        price: <numberBetween(1100,13400)>
        priceCanBeMore: <numberBetween(0,1)>
        duration: <(new \DateInterval('PT45M'))>
        displayableOnProfile: <numberBetween(0,1)>
        onlineBookingDisabled: <numberBetween(0,1)>
        group: @service_group_*
    service_31:
        name: Hajfestés
        description: <paragraph(2)>
        price: <numberBetween(1100,13400)>
        priceCanBeMore: <numberBetween(0,1)>
        duration: <(new \DateInterval('PT45M'))>
        displayableOnProfile: <numberBetween(0,1)>
        onlineBookingDisabled: <numberBetween(0,1)>
        group: @service_group_22
