<?php

namespace Application\Entity;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct($em)
    {
        $entityName = 'Application\Entity\County';
        $class = new ClassMetadata($entityName);

        parent::__construct($em, $class);
    }
}
