<?php

namespace Application\Entity;

use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\Query\Expr\Join;

/**
 * CountyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountyRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct($em)
    {
        $entityName = 'Application\Entity\County';
        $class = new ClassMetadata($entityName);

        parent::__construct($em, $class);
    }

    public function getCountiesWithActiveFeaturedProfessionals()
    {
        return $this->createQueryBuilder('co')
            ->join('co.cities', 'ci')
            ->join('ci.professionals', 'p', Join::WITH, ':now between p.featuredFrom and p.featuredTo')
            ->andWhere('ci.isBigCity <> 1 and ci.isCapital <> 1')
            ->setParameter('now', new \DateTime('now'))
            ->distinct()
            ->orderBy('co.name')
            ->getQuery()->getResult();
    }
}
